name: Samples compilation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
    - name: Setup .NET
      uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3.4.2
      with:
        dotnet-version: 8.x
    - name: Build
      run: dotnet build samples/samples.sln /p:TreatWarningsAsErrors=true
